# Generated by Django 4.2.2 on 2023-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caloriemodel',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='caloriemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='caloriemodel',
            name='met_expectation',
        ),
        migrations.RemoveField(
            model_name='caloriemodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='caloriemodel',
            name='time',
        ),
        migrations.RemoveField(
            model_name='caloriemodel',
            name='user_id',
        ),
    ]
