# Generated by Django 4.2.2 on 2023-06-18 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_caloriemodel_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caloriemodel',
            name='met_expectations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caloriemodel',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='caloriemodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caloriemodel',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caloriemodel',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
