# Generated by Django 4.2.2 on 2023-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caloriemodel_date_caloriemodel_met_expectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriemodel',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
