# Generated by Django 4.2.2 on 2023-06-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_caloriemodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriemodel',
            old_name='text',
            new_name='query',
        ),
    ]
