# Generated by Django 4.2.2 on 2023-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedcalories',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
