# Generated by Django 4.2.2 on 2023-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_diveuser_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveuser',
            name='registration_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diveuser',
            name='registration_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diveuser',
            name='role',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('MANAGER', 'MANAGER'), ('ADMIN', 'ADMIN')], default='REGULAR', max_length=100),
        ),
        migrations.AlterField(
            model_name='diveuser',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
