# Generated by Django 4.2.2 on 2023-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_diveuser_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveuser',
            name='registration_time',
            field=models.TimeField(blank=True),
        ),
    ]
