# Generated by Django 4.2.2 on 2023-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_diveuser_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveuser',
            name='registration_time',
            field=models.TimeField(null=True),
        ),
    ]
